# Generated by Django 2.1 on 2018-08-11 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('companyName', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('county', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('phone1', models.CharField(max_length=12)),
                ('phone2', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=45)),
                ('website', models.CharField(max_length=45)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
